<?php
/**
 * Counter
 *
 * @author WolfThemes
 * @category Core
 * @package %PACKAGENAME%/Admin/Elements
 * @version %VERSION%
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

global $wpb_icons;

// Counter
wpb_add_element(
	array(
		'name' => esc_html__( 'Counter', '%TEXTDOMAIN%' ),
		'description' => esc_html__( 'Animated numerical data', '%TEXTDOMAIN%' ),
		'base' => 'wpb_counter',
		'category' => esc_html__( 'Content', '%TEXTDOMAIN%' ),
		'icon' => 'wpb-icon wpb-counter',
		'params' => array(

			array(
				'type' => 'text',
				'label' => esc_html__( 'Number', '%TEXTDOMAIN%' ),
				'param_name' => 'number',
				'description' => esc_html__( 'It can be a shortcode that generate a number in this case paste your shortcode without the []', '%TEXTDOMAIN%' ),
				'display' => true,
			),

			// array(
			// 	'type' => 'int',
			// 	'label' => esc_html__( 'Duration (in ms)', '%TEXTDOMAIN%' ),
			// 	'param_name' => 'duration',
			// 	'placeholder' => 1000,
			// 	'display' => true,
			// ),

			// array(
			// 	'type' => 'int',
			// 	'label' => esc_html__( 'Delay (in ms)', '%TEXTDOMAIN%' ),
			// 	'param_name' => 'delay',
			// 	'placeholder' => 10,
			// 	'display' => true,
			// ),

			array(
				'type' => 'checkbox',
				'label' => esc_html__( 'Is your number generated by a shortcode?', '%TEXTDOMAIN%' ),
				'param_name' => 'shortcode',
			),
			array(
				'type' => 'text',
				'label' => esc_html__( 'Text', '%TEXTDOMAIN%' ),
				'param_name' => 'text',
				'display' => true,
			),

			array(
				'type' => 'select',
				'label' => esc_html__( 'Add Icon', '%TEXTDOMAIN%' ),
				'param_name' => 'add_icon',
				'choices' => array(
					'no' => esc_html__( 'No', '%TEXTDOMAIN%' ),
					'yes' => esc_html__( 'Yes', '%TEXTDOMAIN%' ),
				),
				'display' => true,
			),

			array(
				'type' => 'icon',
				'label' => esc_html__( 'Icon', '%TEXTDOMAIN%' ),
				'param_name' => 'icon',
				'choices' => $wpb_icons,
				'dependency' => array( 'element' => 'add_icon', 'value' => array( 'yes' ) ),
				'display' => true,
			),
		)
	)
);