<?php
/**
 * Animations
 *
 * @author WolfThemes
 * @category Core
 * @package %PACKAGENAME%/Globals
 * @version %VERSION%
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

$wpb_animations = array(
	'' => esc_html__( 'None', '%TEXTDOMAIN%' ),
	// 'fadeIn' => 'Fade In',
	// 'fadeInUp' => 'Fade In Up',
	// 'fadeInUpBig' => 'Fade In Up Big',
	// 'fadeInDown' => 'Fade In Down',
	// 'fadeInDownBig' => 'Fade In Down Big',
	// 'fadeInLeft' => 'Fade In Left',
	// 'fadeInLeftBig' => 'Fade In Left Big',
	// 'fadeInRight' => 'Fade In Right',
	// 'fadeInRightBig' => 'Fade In Right Big',
	'fadeIn' => 'fadeIn',
	'fadeInDown' => 'fadeInDown',
	'fadeInDownBig' => 'fadeInDownBig',
	'fadeInLeft' => 'fadeInLeft',
	'fadeInLeftBig' => 'fadeInLeftBig',
	'fadeInRight' => 'fadeInRight',
	'fadeInRightBig' => 'fadeInRightBig',
	'fadeInUp' => 'fadeInUp',
	'fadeInUpBig' => 'fadeInUpBig',
	//'fadeOut' => 'fadeOut',
	//'fadeOutDown' => 'fadeOutDown',
	//'fadeOutDownBig' => 'fadeOutDownBig',
	//'fadeOutLeft' => 'fadeOutLeft',
	//'fadeOutLeftBig' => 'fadeOutLeftBig',
	//'fadeOutRight' => 'fadeOutRight',
	//'fadeOutRightBig' => 'fadeOutRightBig',
	//'fadeOutUp' => 'fadeOutUp',
	//'fadeOutUpBig' => 'fadeOutUpBig',
	'bounce' => 'bounce',
	'flash' => 'flash',
	'pulse' => 'pulse',
	'rubberBand' => 'rubberBand',
	'shake' => 'shake',
	'headShake' => 'headShake',
	'swing' => 'swing',
	'tada' => 'tada',
	'wobble' => 'wobble',
	'jello' => 'jello',
	'bounceIn' => 'bounceIn',
	'bounceInDown' => 'bounceInDown',
	'bounceInLeft' => 'bounceInLeft',
	'bounceInRight' => 'bounceInRight',
	'bounceInUp' => 'bounceInUp',
	//'bounceOut' => 'bounceOut',
	//'bounceOutDown' => 'bounceOutDown',
	//'bounceOutLeft' => 'bounceOutLeft',
	//'bounceOutRight' => 'bounceOutRight',
	//'bounceOutUp' => 'bounceOutUp',
	'flipInX' => 'flipInX',
	'flipInY' => 'flipInY',
	//'flipOutX' => 'flipOutX',
	//'flipOutY' => 'flipOutY',
	'lightSpeedIn' => 'lightSpeedIn',
	//'lightSpeedOut' => 'lightSpeedOut',
	'rotateIn' => 'rotateIn',
	'rotateInDownLeft' => 'rotateInDownLeft',
	'rotateInDownRight' => 'rotateInDownRight',
	'rotateInUpLeft' => 'rotateInUpLeft',
	'rotateInUpRight' => 'rotateInUpRight',
	//'rotateOut' => 'rotateOut',
	//'rotateOutDownLeft' => 'rotateOutDownLeft',
	//'rotateOutDownRight' => 'rotateOutDownRight',
	//'rotateOutUpLeft' => 'rotateOutUpLeft',
	//'rotateOutUpRight' => 'rotateOutUpRight',
	'hinge' => 'hinge',
	'rollIn' => 'rollIn',
	//'rollOut' => 'rollOut',
	'zoomIn' => 'zoomIn',
	'zoomInDown' => 'zoomInDown',
	'zoomInLeft' => 'zoomInLeft',
	'zoomInRight' => 'zoomInRight',
	'zoomInUp' => 'zoomInUp',
	//'zoomOut' => 'zoomOut',
	//'zoomOutDown' => 'zoomOutDown',
	//'zoomOutLeft' => 'zoomOutLeft',
	//'zoomOutRight' => 'zoomOutRight',
	//'zoomOutUp' => 'zoomOutUp',
	'slideInDown' => 'slideInDown',
	'slideInLeft' => 'slideInLeft',
	'slideInRight' => 'slideInRight',
	'slideInUp' => 'slideInUp',
	//'slideOutDown' => 'slideOutDown',
	//'slideOutLeft' => 'slideOutLeft',
	//'slideOutRight' => 'slideOutRight',
	//'slideOutUp' => 'slideOutUp',
);